# Generated by Django 2.0.6 on 2018-12-10 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center_votes', models.IntegerField(verbose_name='Votos por centro')),
                ('cloister_votes', models.IntegerField(verbose_name='Votos por claustro')),
            ],
            options={
                'verbose_name_plural': 'Polls',
                'verbose_name': 'Poll',
                'db_table': 'h_votos',
            },
        ),
        migrations.CreateModel(
            name='UniversityGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
            ],
            options={
                'verbose_name_plural': 'UniversityGroups',
                'verbose_name': 'UniversityGroup',
                'db_table': 'd_agrupacion',
            },
        ),
        migrations.CreateModel(
            name='UniversitySchool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
            ],
            options={
                'verbose_name_plural': 'Universities',
                'verbose_name': 'University',
                'db_table': 'd_facultad',
            },
        ),
        migrations.AddField(
            model_name='poll',
            name='university_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='poll.UniversityGroup', verbose_name='Agrupación Universitaria'),
        ),
        migrations.AddField(
            model_name='poll',
            name='university_school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='poll.UniversitySchool', verbose_name='Facultad'),
        ),
    ]
