# Generated by Django 2.0.6 on 2018-12-10 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='year',
            field=models.IntegerField(default=2016, verbose_name='Año'),
            preserve_default=False,
        ),
    ]
