# Generated by Django 2.0.6 on 2018-12-11 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_poll_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='PollYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Año')),
            ],
            options={
                'verbose_name': 'PollYear',
                'verbose_name_plural': 'PollYears',
                'db_table': 'd_year',
            },
        ),
        migrations.AlterField(
            model_name='poll',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='poll.PollYear', verbose_name='Año'),
        ),
    ]
