# Generated by Django 2.0.6 on 2018-12-10 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('latitude', models.CharField(max_length=100, verbose_name='Latitud')),
                ('longitude', models.CharField(max_length=100, verbose_name='Longitud')),
            ],
            options={
                'verbose_name': 'Universidad',
                'verbose_name_plural': 'Universidades',
            },
        ),
        migrations.CreateModel(
            name='UniversityGroupBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('political_block', models.CharField(max_length=100, verbose_name='Bloque político')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'UniversityGroupBlock',
                'verbose_name_plural': 'UniversityGroupBlocks',
            },
        ),
    ]
