# Generated by Django 2.0.6 on 2018-12-10 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='university',
            options={'verbose_name': 'Facultad', 'verbose_name_plural': 'Facultades'},
        ),
    ]
